version: '3.8'

services:
  nuxt:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - laravel
    networks:
      - app_network
  laravel:
    restart: unless-stopped
    container_name: laravel
    build:
      context: ./Backend
      dockerfile: ./Dockerfile

    volumes:
      - ../storage/app:/var/www/html/storage/app
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge